name = "challenge1-azure3tier"
location = "East US"
vnetcidr = "10.0.0.0/16"
websubnetcidr = "10.0.1.0/24"
appsubnetcidr = "10.0.2.0/24"
dbsubnetcidr = "10.0.3.0/24"
web_host_name = "webserver"
web_username = "web_user"
web_os_password = "Webuser@369"
app_host_name = "appserver"
app_username = "app_user"
app_os_password = "Appuser@369"
primary_database = "sql-primary-database2997"
primary_database_admin = "sqladmin"
primary_database_password = "DBuser@369"
primary_database_version = "12.0"

